version: '3.8'
services:
  db: 
    image: mysql:5.7 
    restart: always
    command: --lower_case_table_names=1
    container_name: Probrain_db
    ports:
      - "${DB_PORT}:3306" 
    environment:
      - TZ=Asia/Seoul
      - MYSQL_PORT
    volumes:
      - /Users/Shared/data/Probrain_db:/var/lib/mysql
    # volumes:
    #   - ./db/conf.d:/etc/mysql/conf.d
    #   - ./db/data:/var/lib/mysql
    #   - ./db/initdb.d:/docker-entrypoint-initdb.d
  dev_db: 
    image: mysql:5.7 
    restart: always
    container_name: dev_db
    ports:
      - "${DB_PORT}:3306" 
    environment:
      - TZ=Asia/Seoul
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD} # MYSQL 패스워드 설정 옵션
      - MYSQL_PASSWORD=${DB_PASSWORD}
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
    env_file: .env
    # volumes:
    #   - /Users/Shared/data/dev_db:/var/lib/mysql
    # volumes:
    #   - ./dev/conf.d:/etc/mysql/conf.d
    #   - ./dev/data:/var/lib/mysql
    #   - ./dev/initdb.d:/docker-entrypoint-initdb.d

  redis:
      image: redis:alpine
      container_name: Probrain_redis
      hostname: redis_boot
      env_file: .env
      labels:
        - "name=redis"
        - "mode=standalone"
      ports:
        - ${REDIS_PORT}:6379

  logger-db:
      image: mongo
      restart: always
      container_name: logger-db
      env_file: .env
      environment:
        - TZ=Asia/Seoul
        - MONGO_INITDB_ROOT_USERNAME=${LOGGER_DB_INITDB_ROOT_USERNAME}
        - MONGO_INITDB_ROOT_PASSWORD=${LOGGER_DB_INITDB_ROOT_PASSWORD}
        - MONGO_INITDB_DATABASE=${LOGGER_DB_INITDB_DATABASE}
      
      command: ["-f", "/etc/mongod.conf"]
      ports:
        - ${LOGGER_DB_PORT}:27017
      volumes:
        - ./.docker/logger-db/mongod.conf:/etc/mongod.conf
        # initdb.d/ => container 생성 시 실행, :ro => readOnly
        - ./.docker/logger-db/initdb.d/create-app-user.sh:/docker-entrypoint-initdb.d/create-app-user.sh:ro
        #- ./.docker/mongodb/data/db/:/data/db/
        - ./.docker/logger-db/data/log/:/var/log/mongodb/