version: '3.8'
services:
  nginx-dev:
    image: nginx:latest
    container_name: nginx-dev
    ports:
        - "80:80"
        # - "443:443"
    volumes:
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      #- .docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    # env_file: .env nginx에 env가 들어가지 않음.
    depends_on:
      - node-dev
  nginx:
      image: nginx:latest
      container_name: nginx
      ports:
        - "80:80"
        - "443:433"
      volumes:
        - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      env_file: .env
  node-dev:
    container_name: node-dev
    build:
      context: ./
      target: dev # 도커파일 내 base dev를 build
    volumes:
      - .:/src
    command: yarn dev
    environment:
      DEBUG: nodejs-docker-express:*
    env_file: .env
    depends_on:
      - dev_db
      - redis
      - logger-db
  node:
    container_name: node
    build:
      context: ./
      target: dev # 도커파일 내 base dev를 build
    volumes:
      - .:/src
    command: yarn start
    ports:
      - "3000:3000"
    environment:
      DEBUG: nodejs-docker-express:*
    env_file: .env
  db: 
    image: mysql:5.7 
    restart: always
    command: --lower_case_table_names=1
    container_name: Probrain_db
    volumes:
      - /Users/Shared/data/Probrain_db:/var/lib/mysql
    # volumes:
    #   - ./db/conf.d:/etc/mysql/conf.d
    #   - ./db/data:/var/lib/mysql
    #   - ./db/initdb.d:/docker-entrypoint-initdb.d
  dev_db: 
    image: mysql:5.7 
    restart: always
    container_name: dev_db
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
    env_file: .env
  redis:
      image: redis:alpine
      container_name: Probrain_redis
      hostname: redis_boot
      env_file: .env
      labels:
        - "name=redis"
        - "mode=standalone"

  logger-db:
      image: mongo
      restart: always
      container_name: logger-db
      env_file: .env
      volumes:
        - ./.docker/logger-db/initdb.d/create-app-user.sh:/docker-entrypoint-initdb.d/create-app-user.sh