version: "3"
services:
    test_database:
        container_name: mysql8
        image: mysql:8
        environment:
          MYSQL_ROOT_HOST: "root"
          MYSQL_ROOT_PASSWORD: "qwer1234"
        ports:
          - 3306:3306        
        ulimits:
          memlock:
            soft: -1
            hard: -1
          nofile:
            soft: 65536
            hard: 65536