name: "Push in feature branches"
on:
  push:
    branches:
      - "*/*"
      # - '*'         # matches every branch that doesn't contain a '/'
      # - '*/*'       # matches every branch containing a single '/'
      # - '**'        # matches every branch
      # - '!master'   # excludes master
jobs:
  Lint:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      # 해당 저장소의 코드를 가져옵니다.
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install yarn packages
        run: yarn install
      
      # docker-compose를 활용해 테스트를 위한 컨테이너 환경을 구성합니다.
      - name: ESLINT TEST
        run: yarn lint
